"""Grounded insight synthesis (TECHNICAL_DESIGN.md §2.9).

The reliability rule here is simple and load-bearing: **insights may only
reference values that actually appear in the execution result.** A weak model
asked to "write insights" will happily invent numbers; we forbid that
structurally by building the insight from the code's own printed output.

How grounding works end-to-end:
    - The data-contract requires generated code to ``print()`` a one-line
      plain-English summary of its real computed result (e.g.
      "North leads with revenue 4210; South lowest at 900").
    - The trusted entrypoint captures that stdout and the RESULT line
      (result_shape / artifacts).
    - This node harvests the *printed* lines — the numbers in them were computed
      by pandas from the real data, not generated by the model — and records
      them as the step's insight.

An optional LLM pass may only REPHRASE those grounded lines for readability; it
is given the printed facts and told to add no new numbers. If the model is
unavailable, the raw printed summary is the insight. Either way, no number in an
insight is one the model invented.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from copilot.sandbox.execute import RESULT_SENTINEL


def _printed_lines(stdout: str) -> List[str]:
    """Return the model code's printed summary lines from stdout.

    Excludes the machine-readable RESULT sentinel line and blank lines. These
    lines are the *grounded* facts: pandas computed them from the real data.
    """
    lines: List[str] = []
    for raw in (stdout or "").splitlines():
        line = raw.strip()
        if not line or RESULT_SENTINEL in line:
            continue
        lines.append(line)
    return lines


def ground_insight(execution_result: Dict[str, Any], step: Dict[str, Any]) -> Optional[str]:
    """Build one grounded insight for a successful step, or None if nothing printed.

    Pure and model-free: the returned string contains only text the executed
    code printed (i.e. values computed from the real data) plus the step's own
    description. It never fabricates numbers.
    """
    if not execution_result.get("ok"):
        return None
    printed = _printed_lines(execution_result.get("stdout", ""))
    desc = step.get("desc") or step.get("kind") or "analysis"
    if not printed:
        # A successful step that produced an artifact but printed nothing still
        # gets an honest, number-free line.
        if execution_result.get("artifacts"):
            return f"{desc}: produced a chart (see artifact)."
        return None
    # Take the last printed line as the summary (the contract asks for a single
    # final summary line); keep it tight.
    summary = printed[-1][:300]
    return f"{desc}: {summary}"


def synthesize_insights(
    steps: List[Dict[str, Any]],
    results: List[Dict[str, Any]],
) -> List[str]:
    """Grounded insights across all successful steps. Model-free by default."""
    out: List[str] = []
    for step, res in zip(steps, results):
        ins = ground_insight(res or {}, step or {})
        if ins:
            out.append(ins)
    return out


def polish_with_llm(grounded: List[str], question: str, *, client: Any = None) -> List[str]:
    """OPTIONAL: rephrase grounded lines for readability. Adds no new numbers.

    Falls back to the grounded lines verbatim if the model is unavailable or
    returns anything suspicious. This never runs in the default path; it is here
    so a UI can offer nicer prose without weakening the grounding guarantee —
    the caller passes only the already-grounded facts, and any model failure is
    non-fatal.
    """
    if not grounded:
        return grounded
    try:
        from copilot.llm.client import LLMUnavailable, OllamaClient
        client = client or OllamaClient()
        if hasattr(client, "is_available") and not client.is_available():
            return grounded
        facts = "\n".join(f"- {g}" for g in grounded)
        prompt = (
            f"The user asked: {question}\n\n"
            f"Here are the FACTUAL findings (do not add or change any numbers):\n"
            f"{facts}\n\n"
            "Rewrite them as 1-3 concise plain-English sentences. Use ONLY the "
            "numbers above. Do not invent anything."
        )
        text = client.generate(prompt, system="You are a concise data analyst. Never invent numbers.")
        text = (text or "").strip()
        # Cheap grounding guard: if the model emitted a number not present in the
        # grounded facts, distrust it and fall back.
        import re
        allowed = set(re.findall(r"\d[\d,\.]*", " ".join(grounded)))
        emitted = set(re.findall(r"\d[\d,\.]*", text))
        if emitted - allowed:
            return grounded
        return [text] if text else grounded
    except Exception:
        return grounded
